config/routes.rb
Rails.application.routes.draw do
  resource  :dashboard
  resources :applications do
    resources :steps
  end
  resources :people

  root :to => "dashboards#show"

  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure", as: :login_failure
  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/models/application.rb
class Application < ActiveRecord::Base
  validates_presence_of :company
  validates :status, inclusion: { in: %w(to_apply in_progress applied closed) }

  belongs_to :person
  has_many :steps
  def self.priorities
    %w(high medium low)
  end

  def self.statuses
    %w(to_apply in_progress applied closed)
  end

  def self.tiers
    %w(safety good-fit reach)
  end

  def self.application_search(type)
    where(status: type).order(:company)
  end

  def self.active
    to_apply + in_progress + applied
  end

  def stale?
    stale_date = DateTime.now.utc.beginning_of_day - 5.days
    updated_at <= stale_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include TuringAuth::CurrentUser
  protect_from_forgery with: :exception

  before_action :require_login

  def current_person
    @current_person ||= find_or_create_person
  end
  helper_method :current_person

  def find_or_create_person
    Person.where(:user_github_id => current_user.github_id).first || redirect_to(new_person_path)
  end

  def require_login
    redirect_to login_path unless current_user
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :require_login, except: [:new]
  skip_before_filter :verify_authenticity_token

  def index
  end

  def new
    set_session_url
    @app = Application.new(url: url)
    set_return_path
    clear_session_url if from_bookmarklet_and_logged_in?
  end

  def create
    @app = current_user.applications.new(
      company:      params[:application][:company],
      location:     params[:application][:location],
      url:          params[:application][:url],
      applied_on:   params[:application][:applied_on],
      status:       params[:application][:status],
      contact_info: params[:application][:contact_info],
      tier:         params[:application][:tier],
      priority:     params[:application][:priority]
    )

    save_or_render_new_for_bookmarklet
    clear_session_url
  end

  def show
    @application = Application.find(params[:id])
  end

  def edit
    @app = current_person.applications.find(params[:id])
  end

  def update
    @app = current_person.applications.find(params[:id])

    if params[:status]
      @app.update_attributes(status: params[:status])
    else
      @app.update_attributes(application_params)
    end
    save_or_render_new
  end

  def save_or_render_new
    if @app.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def save_or_render_new_for_bookmarklet
    if @app.save
      redirect_to session[:return_to]
    else
      render :new
    end
  end

  def destroy
    @app = current_person.applications.find(params[:id])
    @app.destroy
    redirect_to dashboard_path
  end

  def submission_confirmation
  end

  private

  def set_return_path
    if from_bookmarklet_and_logged_in?
      session[:return_to] = application_submission_confirmation_path
    elsif from_bookmarklet?
      session[:return_to] = new_application_path(bookmarklet: true)
    else
      session[:return_to] = dashboard_path
    end
  end

  def from_bookmarklet_and_logged_in?
    params[:bookmarklet] && current_user
  end

  def from_bookmarklet?
    params[:bookmarklet]
  end

  def clear_session_url
    session[:url] = ""
  end

  def set_session_url
    session[:url] = params[:url] if params[:url]
  end

  def url
    params[:url] || session[:url]
  end

  def application_params
    params.require(:application).permit(:company,
                                        :location,
                                        :url,
                                        :applied_on,
                                        :status,
                                        :position,
                                        :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def label_for(kind)
    {
      'feedback' => 'label-default',
      'code_challenge' => 'label-info',
      'phone_screen' => 'label-info',
      'culture_interview' => 'label-info',
      'technical_interview' => 'label-info',
      'contracting' => 'label-success'
    }[kind]
  end

  def markdown_renderer
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
  end

  def markdown(content)
    if content
      markdown_renderer.render(content).html_safe
    end
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<div class="application-form">
  <%= semantic_form_for @app do |f| %>
    <%= f.inputs :name => "Basic" do %>
      <%= f.input :company %>
      <%= f.input :location %>
      <%= f.input :url, :label => "URL of the Job Posting" %>
      <%= f.input :applied_on, :as => :string, :input_html => { :value => Date.today } %>
      <%= f.input :status, :as => :select, :collection => Application.statuses %>
      <%= f.input :tier, :as => :select, :collection => Application.tiers %>
      <%= f.input :priority, as: :select, collection: Application.priorities %>
      <%= f.input :position, label: "Position" %>
      <%= f.input :contact_info, label: "Contact Information", input_html: { class: 'autogrow', rows: 5, cols: 10 } %>
      <%= f.input :notes, label: "Notes" %>
    <% end %>
    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/applications/edit.html.haml
%h2 Edit Your Application

= render :partial => 'form'

app/views/applications/new.html.erb
<% if logged_in? %>
  <h2 id="create_application">Create an Application</h2>
  <%= render :partial => 'form' %>
<% else %>
  <h6 id="bookmarklet_login_msg"> Please Login Before Submitting Applications </h6>
  <%= link_to "Log in with GitHub", login_path, class: "btn btn-primary" %>
<% end %>

app/views/applications/show.html.erb
<div class="application">

  <%= render :partial => "partials/company_details_table" %>

  <ul class="actions">
    <li>
      <%= link_to "Edit", edit_application_path(@application), :id => "edit_application_#{@application.id}" %>
    </li>
  </ul>
  <h2>Recorded Steps</h2>

  <%= button_to "Add a Step", new_application_step_path(@application), :id => 'add_step', :class => "btn btn-default", :method => :get %>

  <%= render :partial => "partials/display_steps_and_edit_buttons" %>

</div>

app/views/applications/submission_confirmation.html.erb
<h3 id="form_confirmation_message">Your application has been added to your dashboard. </h3>
<script charset="utf-8">
setTimeout(function(){window.close("windowName")}, 1500)
</script>