config/routes.rb
Rails.application.routes.draw do
  resource  :dashboard
  resources :applications do
    resources :steps
  end
  resources :people

  root :to => "dashboards#show"

  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure", as: :login_failure
  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/views/partials/_applied_applications.html.erb
<div class="applied">
  <div class="column" data-status="applied">
    <h2>Applied</h2>
    <%= render :partial => "application", :collection => @applied_applications %>
  </div>
</div>

app/views/partials/_closed_applications.html.erb
<div class="closed">
  <div class="column" data-status="closed">
    <h2>Closed</h2>
    <%= render :partial => "application", :collection => @closed_applications %>
  </div>
</div>

app/views/partials/_company_details_table.html.erb
<h1><%= @application.company %></h1>
<table class="table table-striped">
  <tr>
    <th>Location</th>
    <td>
      <%= @application.location %>
    </td>
  </tr>
  <tr>
    <th>URL</th>
    <td>
      <%= link_to @application.url, @application.url %>
    </td>
  </tr>
  <tr>
    <th>Applied On</th>
    <td>
      <%= @application.applied_on %>
    </td>
  </tr>
  <tr>
    <th>Tier</th>
    <td>
      <%= @application.tier %>
    </td>
  </tr>
  <tr>
    <th>Priority</th>
    <td>
      <%= @application.priority %>
    </td>
  </tr>
  <tr>
    <th>Position</th>
    <td>
      <%= @application.position %>
    </td>
  </tr>
  <tr>
    <th>Status</th>
    <td>
      <%= @application.status %>
    </td>
  </tr>
  <tr>
    <th>Contact Information</th>
    <td>
      <%= @application.contact_info %>
    </td>
  </tr>
</table>
<tr>
  <th>Notes</th>
  <td>
    <%= @application.notes %>
  </td>
</tr>
</table>

app/views/partials/_display_steps_and_edit_buttons.html.erb
<% @application.steps.order(:created_at).each do |step| %>
  <div class="step <%= step.kind %>">
    <h3>
      <%= step.kind.humanize %>
    </h3>
    <%= markdown(step.note) %>
    <ul class="actions">
      <li>
        <%= link_to "Edit", edit_application_step_path(@application, step), :id => "edit_step_#{step.id}" %>
      </li>
      <li>
        <%= link_to "Delete", application_step_path(@application, step), :id => "delete_step_#{step.id}", :method => :delete %>
      </li>
    </ul>
  </div>
<% end %>

app/views/partials/_in_progress_applications.html.erb
<div class="in_progress">
  <div class="column" data-status="in_progress">
    <h2>In Progress</h2>
    <%= render :partial => "application", :collection => @in_progress_applications %>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dboard_link"><a href="/dashboard">Dashboard</a></li>

          <li class="dboard_link"><%= link_to "Log out", logout_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_to_apply_applications.html.erb
<div class="to_apply">
  <div class="column" data-status="to_apply">
    <h2>To Apply</h2>
    <%= render :partial => "application", :collection => @to_apply_applications %>
  </div>
</div>