config/routes.rb
Rails.application.routes.draw do
  resource  :dashboard
  resources :applications do
    resources :steps
  end
  resources :people

  root :to => "dashboards#show"

  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure", as: :login_failure
  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :application

  def self.kinds
    %W(feedback code_challenge phone_screen culture_interview technical_interview contracting)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :load_application

  def load_application
    @application = Application.find(params[:application_id])
  end

  def new
    @step = @application.steps.new
  end

  def create
    @step = @application.steps.new(
      :kind => params[:step][:kind],
      :note => params[:step][:note]
    )

    if @step.save
      redirect_to @application
    else
      render :new
    end
  end

  def edit
    @step = @application.steps.find(params[:id])
  end

  def update
    @step = @application.steps.find(params[:id])
    @step.kind = params[:step][:kind]
    @step.note = params[:step][:note]

    if @step.save
      redirect_to @application
    else
      render :edit
    end
  end

  def destroy
    @step = @application.steps.find(params[:id])
    @step.destroy
    redirect_to @application
  end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.haml
= f.inputs :name => 'Application Step' do
  = f.input :kind, :as => :select, :collection => Step.kinds
  = f.input :note

= f.submit "Save"

app/views/steps/edit.html.haml
%h2= "Edit a Step for #{@application.company}"

= semantic_form_for @step, :url => application_step_path(@application.id, @step.id) do |f|
  = render :partial => 'form', :locals => {:f => f}

app/views/steps/new.html.haml
%h2= "Add a Step for #{@application.company}"

= semantic_form_for @step, :url => application_steps_path(@application.id) do |f|
  = render :partial => 'form', :locals => {:f => f}