config/routes.rb
Rails.application.routes.draw do
  resource  :dashboard
  resources :applications do
    resources :steps
  end
  resources :people

  root :to => "dashboards#show"

  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure", as: :login_failure
  get '/login' => 'sessions#new', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :require_login

  def show
    unless current_person.is_a? String
      @to_apply_applications = searcher("to_apply")
      @closed_applications = searcher("closed")
      @in_progress_applications = searcher("in_progress")
      @applied_applications = searcher("applied")
    end
  end

  private

  def searcher(status)
    current_user.applications.application_search(status)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboards/_application.html.erb
<div class="portlet" data-application-id="<%= application.id %>">
  <div class="portlet-header">
    <%= link_to application.company, application %>
  </div>

  <div class="portlet-content">
    <% if application.stale? %>
      <p class="stale_message">"Application hasn't been updated in over 5 days"</p>
    <% end %>
    <%= link_to 'edit', edit_application_path(application) %>
    <%= " | " %>
    <%= link_to 'remove', application_path(application), :method => :delete %>
  </div>
</div>

app/views/dashboards/show.html.erb
<div id="create_application_btn">
  <%= button_to "Create a New Application", new_application_path, :id => "new_application", class: "btn btn-default", :method => :get %>
</div>

<div id="bookmarklet">
  <a class="btn-xs btn btn-default", style="padding-bottom: 3px", href="javascript:window.open('<%= ENV['bookmarklet_base'] %>' +'/applications/new?url='
    +encodeURIComponent(location.href)+'&bookmarklet=true', 'windowName', 'width=600,height=500,resizable,scrollbars=yes,status=1');">
    Drag to Your Favorites Bar to Add Applications From Any Page</a></li>
  </div>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render :partial => "partials/to_apply_applications" %>
    </div>
    <div class="col-md-3">
      <%= render :partial => "partials/in_progress_applications" %>
    </div>
    <div class="col-md-3">
      <%= render :partial => "partials/applied_applications" %>
    </div>
    <div class="col-md-3">
      <%= render :partial => "partials/closed_applications" %>
    </div>
  </div>
</div>